# Setup
title: Xylophone
subtitle: Personal Blog
description: Hi there, welcome!
url: https://xyzdeclan.github.io
avatar: /avatar.jpeg
avatarTitle: Declan X
avatarDesc: Master of Data Science Student @UniMelb
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
logo: logo.png
social:
  name: Yizong Xing
  links:
    # - https://twitter.com/vszhub
    - https://github.com/xyzdeclan
  mail: 
    - xyzdeclan@gmail.com
    - yizongx@student.unimelb.edu.au
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Yizong Xing
  url: https://github.com/xyzdeclan/
  email: vszhub@gmail.com


